### ISSUE TITLE
Injector breaks compatibility with TypePicker mod

### ISSUE THREAD

**Issue by Nytra** [ResoniteModdingGroup/ComponentSelectorAdditions#3]
TypePicker mod: https://github.com/TheJebForge/TypePicker

When Injector is turned off, TypePicker works again, but then search doesn't work

**Comment by Banane9** [comment]
Hmmm, the incompatibility is expected, considering it also patches UI generation. It could be ported to integrate into this system, either directly or as a standalone mod... though currently the generic type picker UI generation isn't directly exposed 🤔

**Comment by Banane9** [comment]
Just asked Jeb about porting it, but got a too busy as a reply, so one of us would have to do it if that's desired.

**Comment by Banane9** [comment]
Added this as a note to the readme now. I also added an event that would support porting the mod.

**Comment by Banane9** [comment]
Fixed ;)

https://github.com/ResoniteModdingGroup/TypePicker
