### ISSUE TITLE
Feature Request: Result button size adjustment

### ISSUE THREAD

**Issue by EuphieEuphoria** [ResoniteModdingGroup/ComponentSelectorAdditions#7]
For better readability, a slider or value field that adjusts the height of result buttons would be very nice.

![image](https://github.com/user-attachments/assets/3d73d053-7d8d-477a-913b-62a2a76495ad)

**Comment by Banane9** [comment]
What range do you think would make sense? 32 is the default height.

**Comment by EuphieEuphoria** [comment]
I tested up to a size of 60, anything larger than that would cause the text to become overbearing. I think a range between 32 and 64 would work nicely

**Comment by Banane9** [comment]
![Component Selector with thicker buttons](https://github.com/user-attachments/assets/4e8cbebe-b339-40a6-9d0c-02c1d0d59e80)
